import type { Metadata } from "next";
import "../../app/globals.css";
import Headerv2 from "@/app/components/HomePage/Headerv2";
import { Space_Grotesk } from "next/font/google";
import Footer from "@/app/components/HomePage/Footer";
import Script from "next/script";
import { getNavServices } from "@/app/lib/services/get-nav-services";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "GS Digital",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navigation = await getNavServices();

  return (
    <html lang="en">
      <head>{/* Google Tag Manager Script */}</head>
      <body>
        <Headerv2 navigation={navigation} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
