import type { Metadata } from "next";
import "../../app/globals.css";
import Head from "next/head";
import { Space_Grotesk } from "next/font/google";
import Script from "next/script";


const spaceGrotesk = Space_Grotesk({ subsets: ['latin'], weight: ["300", "400", "500", "600", "700"] });

export const metadata: Metadata = {
  title: "Global Surf Digital",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>    <script dangerouslySetInnerHTML={{__html: `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src= 'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f); })(window,document,'script','dataLayer','GTM-TVWCC3XC');`, }} /></Head>
      <body>
      <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-TVWCC3XC"height="0"width="0"style={{ display: "none", visibility: "hidden" }}           /></noscript>
        {children}
        <Script
        id="zoho-salesiq"
        strategy="afterInteractive"
        dangerouslySetInnerHTML={{
          __html: `
            window.$zoho=window.$zoho || {};
            $zoho.salesiq = $zoho.salesiq || {
              ready: function() {}
            };
          `,
        }}
      />
        <script id="zsiqscript" src="https://salesiq.zohopublic.com/widget?wc=siqfbc0d98490746e45b5054af7cb63167d80bb738150df87ecb255b37f30af3c7c" defer></script>

      </body>
    </html>
  );
}
