import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import {Space_Grotesk, Lexend} from "next/font/google";
import Footer from "./components/Footer";


const lexend = Lexend({subsets: ['latin'] ,weight:["300","400","500","600","700"] });
const spaceGrotesk = Space_Grotesk({subsets: ['latin'] ,weight:["300","400","500","600","700"] });


export const metadata: Metadata = {
  title: "Global Surf Digital",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${spaceGrotesk.className} antialiased`}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
