import type { Metadata } from "next";
import "../../app/globals.css";
import Header from "@/app/components/HomePage/Header";
import { Space_Grotesk } from "next/font/google";
import Footer from "@/app/components/HomePage/Footer";


const spaceGrotesk = Space_Grotesk({ subsets: ['latin'], weight: ["300", "400", "500", "600", "700"] });

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Global Surf Digital",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
